# Generated by Django 2.2.28 on 2026-03-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmySearchRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500, verbose_name='запрос')),
                ('expected_limit', models.PositiveSmallIntegerField(default=10, verbose_name='ожидаемый максимум результатов')),
                ('search_url', models.URLField(max_length=2048, verbose_name='URL поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('status', models.CharField(choices=[('pending', 'в процессе'), ('ok', 'успех'), ('error', 'ошибка')], db_index=True, default='pending', max_length=16, verbose_name='статус')),
                ('error_message', models.TextField(blank=True, verbose_name='текст ошибки')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='сохранено записей')),
            ],
            options={
                'verbose_name': 'запуск поиска Firmy',
                'verbose_name_plural': 'запуски поиска Firmy',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FirmySearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(db_index=True, verbose_name='позиция в выдаче')),
                ('premise_id', models.PositiveIntegerField(db_index=True, verbose_name='premise id')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('detail_url', models.URLField(max_length=2048, verbose_name='ссылка на профиль')),
                ('category', models.CharField(blank=True, max_length=300, verbose_name='категория')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='адрес')),
                ('card_text', models.TextField(blank=True, verbose_name='текст карточки (сырой)')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='firmy.FirmySearchRun', verbose_name='запуск')),
            ],
            options={
                'verbose_name': 'результат Firmy',
                'verbose_name_plural': 'результаты Firmy',
                'ordering': ('run', 'position'),
                'unique_together': {('run', 'position'), ('run', 'premise_id')},
            },
        ),
    ]
