# Generated by Django 2.2.28 on 2026-03-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmysearchresult',
            name='emails',
            field=models.TextField(blank=True, help_text='по одному на строку', verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='firmysearchresult',
            name='phones',
            field=models.TextField(blank=True, help_text='нормализованные номера, по одному на строку', verbose_name='телефоны'),
        ),
    ]
