# Generated by Django 2.2.28 on 2026-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0002_add_phones_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmysearchresult',
            name='website_url',
            field=models.URLField(blank=True, help_text='ссылка с профиля (часто кнопка «Web» — может вести на соцсеть)', max_length=2048, verbose_name='сайт'),
        ),
    ]
