# Generated by GPT for Django 2.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firmy", "0004_premise_and_hit"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmyProcessingItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="добавлено в обработку")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлено")),
                ("was_contacted", models.BooleanField(default=False, verbose_name="был ли контакт")),
                ("was_answered", models.BooleanField(default=False, verbose_name="был ли ответ")),
                (
                    "conversation_json",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text='JSON-массив сообщений, например: [{"ts":"2026-03-26T12:00:00Z","dir":"out","text":"..."}]',
                        verbose_name="переписка (JSON массив)",
                    ),
                ),
                (
                    "premise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_item",
                        to="firmy.FirmyPremise",
                        verbose_name="карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "обработка Firmy",
                "verbose_name_plural": "обработка Firmy",
                "ordering": ("-created_at",),
            },
        ),
    ]

