# Generated by GPT for Django 2.2

from django.db import migrations, models
from django.utils import timezone


def forwards_set_queued_at(apps, schema_editor):
    FirmyProcessingItem = apps.get_model("firmy", "FirmyProcessingItem")
    now = timezone.now()
    for it in FirmyProcessingItem.objects.filter(queued_at__isnull=True).iterator():
        it.queued_at = it.created_at or now
        it.save(update_fields=["queued_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("firmy", "0005_processing_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmyprocessingitem",
            name="queued_at",
            field=models.DateTimeField(db_index=True, default=timezone.now, verbose_name="в очереди с"),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_set_queued_at, migrations.RunPython.noop),
    ]

