# Generated by Django 4.2.27 on 2026-03-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0006_processing_queue_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmyprocessingitem',
            options={'ordering': ('queued_at', 'id'), 'verbose_name': 'обработка Firmy', 'verbose_name_plural': 'обработка Firmy'},
        ),
    ]
