# Generated by Django 4.2.27 on 2026-03-26 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0013_processing_generation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmyprocessingitem',
            name='queued_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='в очереди с'),
        ),
    ]
